### ISSUE TITLE
Matching 'collection' and 'title' fields for collection objects in 'navigation.yml'

### ISSUE THREAD

**Issue by kwajiehao** [isomerpages/isomerpages-template#166]
Currently, the `title` and `collection` field for a collection object in `navigation.yml` are not tied to each other. For example, EDB-OSP's navigation file (https://github.com/isomerpages/edb-osp/blob/staging/_data/navigation.yml) looks like this:

```
logo: /images/sgn-logo.svg

favicon: /images/favicon-globe.ico

links:
  - title: About us
    url: /about-us/
  - title: Things to do
    collection: events
  - title: Food for thought
    resource_room: true
  - title: Resources
    collection: resources
  - title: Funding
    url: /funding/
  - title: Keep in touch
    url: /keep-in-touch/
```

The second object in `links` has `title` of `Things to do` but the `collection` field is `events`. This presents inconsistencies when we are rendering the drag and drop menu page. To allow user flexibility in controlling whether a collection should be displayed on the navigation bar **through** the drag and drop menu, we need information on the collection's title. 

However, when constructing the drag and drop menu, we only have information on the `title` field for collections **already** in the navigation bar, which means we will not render "hidden" collections with the right title in the drag and drop menu, since we do not have access to the `title` field.

I propose that the `collection` name should always be a slugified version of the `title` of the collection so that we can easily recover the `title` from the `collection`.
